---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    include-labels:
      - "breaking-change"
      - "major"
    semver-increment: major
  - title: "✨ New features"
    include-labels:
      - "new-feature"
      - "minor"
    semver-increment: minor
  - title: "🐛 Bug fixes"
    include-labels:
      - "bugfix"
    semver-increment: patch
  - title: "🚀 Enhancements"
    include-labels:
      - "enhancement"
      - "refactor"
      - "performance"
    semver-increment: patch
  - title: "🧰 Maintenance"
    include-labels:
      - "chore"
      - "ci"
    semver-increment: patch
  - title: "📚 Documentation"
    include-labels:
      - "documentation"
    semver-increment: patch
  - title: "⬆️ Dependency updates"
    include-labels:
      - "dependencies"
    collapse-after: 5
    semver-increment: patch

version-resolver:
  default: patch

template: |
  ## What’s changed

  $CHANGES
