---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
sort-direction: ascending

categories:
  - title: "🚨 Breaking changes"
    semver-increment: major
    when:
      labels:
        - "breaking-change"
        - "major"
  - title: "✨ New features"
    semver-increment: minor
    when:
      labels:
        - "new-feature"
        - "minor"
  - title: "🐛 Bug fixes"
    semver-increment: patch
    when:
      labels:
        - "bugfix"
  - title: "🚀 Enhancements"
    semver-increment: patch
    when:
      labels:
        - "enhancement"
        - "refactor"
        - "performance"
  - title: "🧰 Maintenance"
    semver-increment: patch
    when:
      labels:
        - "chore"
        - "ci"
  - title: "📚 Documentation"
    semver-increment: patch
    when:
      labels:
        - "documentation"
  - title: "⬆️ Dependency updates"
    collapse-after: 5
    semver-increment: patch
    when:
      labels:
        - "dependencies"

version-resolver:
  default: patch

template: |
  ## What’s changed

  $CHANGES
